### ISSUE TITLE
Not an issue but query

### ISSUE THREAD

**Issue by Naman23-coder** [pytogo/portforward#1]
How did you convert .go file into python runnable ???
I know there is a c file with python.h but I am still confused

**Comment by corka149** [comment]
It uses `setuptools-golang`(see requirements-dev.txt) in the setup.py. 

```Python
    ext_modules=[
        Extension(
            "portforward", ["main.go"],
            py_limited_api=True, define_macros=[('Py_LIMITED_API', None)],
        )
    ]
```

When the Go compiler sees `import "C"` it will look around in the same folder for C files and tries also to compile them.

(TODO: Update the README. The README is quit empty at this point. )

**Comment by corka149** [comment]
[Updated readme](https://github.com/pytogo/portforward/commit/161dc4a2a3ba172631aa072000b1547e71dfa7d3)

Feel free to open the issue again when you have further questions.
