### ISSUE TITLE
$KUBECONFIG env variable is ignored

### ISSUE THREAD

**Issue by atti92** [pytogo/portforward#15]
https://github.com/pytogo/portforward/blob/f42e688ba624c57798ec1ccb91fa852fe67d3833/portforward.py#L133

This should be the same as in the official kubernetes client:
https://github.com/kubernetes-client/python/blob/master/kubernetes/base/config/kube_config.py#L48

**Comment by corka149** [comment]
Hi @atti92 

thanks for the hint. I changed it. It will be included in release v0.4.0.
