### ISSUE TITLE
Request: In-cluster configuration

### ISSUE THREAD

**Issue by atti92** [pytogo/portforward#16]
* portforward version: 0.4.1
* Python version: 3.10
* Operating System: Linux
Referenced issue: https://github.com/pytogo/pytogo/issues/2

### Description

We are trying to use this package in all kinds of scenarios, and one of those is running the code in a Job/Pod in the cluster. Currently the package demands a kube.config file. I suggest adding the Incluster config loading fallback to the Go code:
[Example](https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L41)

### What I Did
Currently we are trying to work around this issue by generating a kube.config file dynamically, but it is not a great solution.

**Comment by corka149** [comment]
Hi @atti92 

thanks for the nice issue & hint/code snippet. I added the feature and it will be release today as `0.4.2`.
