### ISSUE TITLE
Portforward 0.4.3 hanging forever with pytest

### ISSUE THREAD

**Issue by alaeddine-13** [pytogo/portforward#18]
* portforward version: 0.4.3
* Python version: Python 3.8.8
* Operating System: Ubunutu 18.0.4

### Description

It looks like portforward when used within a pytest environment, it will hang forever.
In [Jina's CI tests](https://github.com/jina-ai/jina/blob/master/tests/k8s/test_k8s_flow.py#L137), we use portforward to test deployed services.
However, since the latest 0.4.3, the CI will hang forever right when portforward is called. Therefore, we had to limit the portforward version to 0.4.2

### What I Did

in a pytest script, do portforwarding to any pod:
```python
with portforward.forward(
    namespace, pod_name, port, port, config_path
):
```
this will hang forever

**Comment by corka149** [comment]
Hi @alaeddine-13 

thx for your report.

I found the issue and fix it. The version 0.4.4 will be released today.
