### ISSUE TITLE
Provide a Python 3.12 wheel

### ISSUE THREAD

**Issue by EraYaN** [pytogo/portforward#37]
* portforward version: latest
* Python version: 3.12
* Operating System: Linux

### Description

PLease provide a 3.12 wheel, the dependency on rust is a pretty large burden for a simple pip install. c compilers are almost always there but no rust toolchain.

### What I Did

```
pip install portforward
```

**Comment by corka149** [comment]
Hi @EraYaN 

sure I will upload them today and tomorrow.

**Comment by corka149** [comment]
The wheels are available for windows, macos and Linux for x86_64. For ARM I have to start working on a GitHub release action this weekend.

**Comment by EraYaN** [comment]
Thanks! That works for us. I'll leave this open to track the ARM wheels.

**Comment by corka149** [comment]
I created a Github action that builds several new wheels. (Including x64 and aarch64)

Now a new python version and new lib release should be a breeze. :smile:
