### ISSUE TITLE
Bind to 0.0.0.0

### ISSUE THREAD

**Issue by SuperTyrael** [pytogo/portforward#38]
portforward version: latest
Python version: 3.12
Operating System: Linux

### Description

Hi, is there any way to bind to 0.0.0.0? Since I find forwarder bind to 127.0.0.1 by default. I need the function to build a jump server.

### What I Did

```
pip install portforward
```

**Comment by corka149** [comment]
Hi @SuperTyrael . This looks doable. I am a bit short on time but will start soon.

**Comment by corka149** [comment]
The feature was added and released as version 0.6.2. The IP address can be configured with the parameter `bind_ip`.
