### ISSUE TITLE
[HowTo] Use portforward.forward without 'with' keyword and manage close timing manually?

### ISSUE THREAD

**Issue by KSroido** [pytogo/portforward#41]
* portforward version:
* Python version:
* Operating System:

### Description

```
with portforward.forward(namespace, pod_name, local_port, pod_port):
        response = requests.get("http://localhost:9000")
        print(f"Done: \n'{response.status_code}'\n'{response.text[:20]}...'")

```

Use portforward.forward without 'with' keyword and manage close timing manually,

is that possible in current version?

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by corka149** [comment]
Hi @KSroido , yes just create a new object of async portforwarder or portforwarder and invoke the wanted methods on that object.

See https://portforward.readthedocs.io/en/latest/portforward.html#module-portforward

**Comment by KSroido** [comment]
OK thanks for your advice :)
