### ISSUE TITLE
Is this possible to portforward localhost:port1 to 1.2.3.4:port2 with this package?

### ISSUE THREAD

**Issue by KSroido** [pytogo/portforward#42]
* portforward version:
* Python version:
* Operating System:

Is this possible to portforward localhost:port1 to 1.2.3.4:port2 with this package?

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by corka149** [comment]
Hi @KSroido , yes just create a new object of async portforwarder or portforwarder and invoke the wanted methods on that object.

See https://portforward.readthedocs.io/en/latest/portforward.html#module-portforward

**Comment by corka149** [comment]
Hi @KSroido. In a pod? Or what is the relationship to kubernetes in your question?

**Comment by KSroido** [comment]
I'm sorry, I have find a solution which is more suitable for my situation. I forgot to close this issue

ref: https://gist.github.com/WangYihang/e7d36b744557e4673d2157499f6c6b5e
